#!/usr/bin/env python3
"""Step 4: Reference-frame selection and background-subtracted geometry.

Selects a reference frame M and computes Z_prime = Z_def - Z_def[M] to
remove background curvature before circle fitting.

Paper reference:
    Min et al. (2017), Sec. 2.1 step (ii):
    "By taking the M-th frame as the reference image, new (Y, Z')
     coordinates are generated by:
         Z'_{i,j}(k) = Z_{i,j}(k) - Z_{i,j}(M)"         (Eq. 1)

    NOTE: This Z-based subtraction is the Marciniak branch (flat punch).
    For Nakazima tests (hemispherical punch), use the (D, R^Out) branch
    in nakazima_transform.py instead. Running this Z-based path on
    Nakazima data is valid for diagnostic comparison only — the results
    are not physically correct for hemispherical-punch geometry.

Usage:
    from curvature_matrix import build_curvature_matrix
    from reference_subtraction import ReferenceConfig, apply_reference_subtraction

    mat = build_curvature_matrix(dic, region)
    ref = apply_reference_subtraction(mat)
    print(ref.report())
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

import numpy as np

from curvature_matrix import CurvatureMatrixData


# ---------------------------------------------------------------------------
#  Configuration
# ---------------------------------------------------------------------------

@dataclass
class ReferenceConfig:
    """Configuration for reference-frame selection.

    Paper guidance:
        - Marciniak: M roughly ½F (Sec. 2.1)
        - Nakazima: M after the specimen fully wraps onto the punch (Sec. 2.2)

    Default here: M = floor(reference_fraction * last_valid_frame_index).
    """

    # Fraction of the last valid frame index to use as M
    reference_fraction: float = 0.75

    # Manual override: if set, use this frame index directly
    reference_frame_index: Optional[int] = None

    # Minimum valid fraction required at frame M
    min_valid_fraction_at_M: float = 0.90

    # Minimum gap between M and crack frame [frames]
    min_gap_to_crack: int = 10

    # Skip this many initial frames (settling/contact phase)
    skip_initial_frames: int = 2


# ---------------------------------------------------------------------------
#  Result container
# ---------------------------------------------------------------------------

@dataclass
class ReferenceSubtractionResult:
    """Background-subtracted geometry with reference-frame metadata."""

    # --- Background-subtracted height ---
    # Z_prime[k, p] = Z_def[k, p] - Z_def[M, p]
    # shape: (n_frames, n_sel)
    Z_prime: np.ndarray

    # --- X_def, Y_def unchanged (pass through for convenience) ---
    X_def: np.ndarray              # (n_frames, n_sel)
    Y_def: np.ndarray              # (n_frames, n_sel)

    # --- Reference frame info ---
    M: int                         # reference frame index (into time axis)
    M_frame_id: int                # actual frame ID at M
    M_time: float                  # time [s] at M
    selection_method: str          # how M was chosen

    # --- Statistics ---
    Z_prime_stats_before_M: dict   # mean, std, max_abs for frames < M
    Z_prime_stats_after_M: dict    # mean, std, max_abs for frames > M
    valid_fraction_at_M: float

    # --- Source data reference ---
    mat: CurvatureMatrixData       # parent matrix data (for chaining)

    warnings: List[str] = field(default_factory=list)

    def report(self) -> str:
        """Human-readable summary."""
        sb = self.Z_prime_stats_before_M
        sa = self.Z_prime_stats_after_M
        lines = [
            f"ReferenceSubtractionResult",
            f"",
            f"  reference frame M:        index {self.M}, "
            f"frame_id {self.M_frame_id}, t={self.M_time:.3f} s",
            f"  selection method:         {self.selection_method}",
            f"  valid fraction at M:      {self.valid_fraction_at_M:.1%}",
            f"",
            f"  Z_prime before M:         "
            f"mean={sb['mean']:.6f}, std={sb['std']:.6f}, "
            f"max|Z'|={sb['max_abs']:.6f}",
            f"  Z_prime after M:          "
            f"mean={sa['mean']:.6f}, std={sa['std']:.6f}, "
            f"max|Z'|={sa['max_abs']:.6f}",
            f"",
            f"  warnings:                 "
            f"{', '.join(self.warnings) if self.warnings else 'none'}",
        ]
        return "\n".join(lines)

    def __repr__(self) -> str:
        return (
            f"ReferenceSubtractionResult(M={self.M}, "
            f"frame_id={self.M_frame_id}, "
            f"t={self.M_time:.3f}s, "
            f"method='{self.selection_method}')"
        )


# ---------------------------------------------------------------------------
#  Reference frame selection
# ---------------------------------------------------------------------------

def _select_reference_frame(
    mat: CurvatureMatrixData,
    cfg: ReferenceConfig,
) -> tuple:
    """Select the reference frame index M.

    Returns
    -------
    M : int
        Frame index into the time/frame arrays.
    method : str
        Description of how M was chosen.
    warnings : list of str
    """
    warnings: List[str] = []
    n_frames = len(mat.time)
    qm = mat.quality_metrics
    valid_frac = qm.valid_fraction_per_frame

    # --- Manual override ---
    if cfg.reference_frame_index is not None:
        M = int(cfg.reference_frame_index)
        M = max(0, min(M, n_frames - 1))
        method = f"manual override (index {cfg.reference_frame_index})"

        if valid_frac[M] < cfg.min_valid_fraction_at_M:
            warnings.append(
                f"Manual M={M}: valid fraction {valid_frac[M]:.3f} "
                f"< threshold {cfg.min_valid_fraction_at_M:.3f}"
            )
        return M, method, warnings

    # --- Automatic selection ---
    # Last valid frame index
    last_valid_idx = qm.last_fully_valid_frame_index

    # Compute candidate M
    M = int(np.floor(cfg.reference_fraction * last_valid_idx))

    # Enforce bounds
    M = max(cfg.skip_initial_frames, M)
    M = min(M, n_frames - 1)

    method = (
        f"floor({cfg.reference_fraction} * last_valid_idx={last_valid_idx}) "
        f"= {M}"
    )

    # --- Validate M ---

    # Check valid coverage at M
    if valid_frac[M] < cfg.min_valid_fraction_at_M:
        # Search nearby for a frame with better coverage
        best_M = M
        best_frac = valid_frac[M]
        search_range = range(
            max(cfg.skip_initial_frames, M - 10),
            min(n_frames, M + 11),
        )
        for candidate in search_range:
            if valid_frac[candidate] > best_frac:
                best_frac = valid_frac[candidate]
                best_M = candidate
        if best_M != M:
            warnings.append(
                f"Shifted M from {M} to {best_M} for better coverage "
                f"({valid_frac[M]:.3f} -> {best_frac:.3f})"
            )
            M = best_M
            method += f" -> adjusted to {M} (coverage)"

        if valid_frac[M] < cfg.min_valid_fraction_at_M:
            warnings.append(
                f"Valid fraction at M={M} is {valid_frac[M]:.3f}, "
                f"below threshold {cfg.min_valid_fraction_at_M:.3f}"
            )

    # Check gap to crack frame
    if mat.crack_frame is not None:
        crack_idx = None
        for i, fid in enumerate(mat.frame_ids):
            if fid >= mat.crack_frame:
                crack_idx = i
                break
        if crack_idx is None:
            crack_idx = n_frames  # crack is beyond loaded frames

        gap = crack_idx - M
        if gap < cfg.min_gap_to_crack:
            warnings.append(
                f"M={M} is only {gap} frames before crack "
                f"(minimum: {cfg.min_gap_to_crack})"
            )

    # Check not too early
    if M < cfg.skip_initial_frames:
        warnings.append(
            f"M={M} is in the initial settling phase "
            f"(skip_initial_frames={cfg.skip_initial_frames})"
        )

    return M, method, warnings


# ---------------------------------------------------------------------------
#  Z_prime statistics
# ---------------------------------------------------------------------------

def _z_prime_stats(Z_prime: np.ndarray, valid: np.ndarray, frame_mask: np.ndarray) -> dict:
    """Compute mean, std, max_abs of Z_prime over selected frames."""
    if not np.any(frame_mask):
        return {"mean": 0.0, "std": 0.0, "max_abs": 0.0}

    vals = Z_prime[frame_mask]
    v = valid[frame_mask]
    data = vals[v] if v.any() else vals.ravel()

    if len(data) == 0:
        return {"mean": 0.0, "std": 0.0, "max_abs": 0.0}

    return {
        "mean": float(np.nanmean(data)),
        "std": float(np.nanstd(data)),
        "max_abs": float(np.nanmax(np.abs(data))),
    }


# ---------------------------------------------------------------------------
#  Main entry point
# ---------------------------------------------------------------------------

def apply_reference_subtraction(
    mat: CurvatureMatrixData,
    cfg: Optional[ReferenceConfig] = None,
) -> ReferenceSubtractionResult:
    """Select reference frame M and compute Z_prime = Z_def - Z_def[M].

    Parameters
    ----------
    mat : CurvatureMatrixData
        Output of build_curvature_matrix() (Step 3).
    cfg : ReferenceConfig, optional
        Configuration. Uses defaults if None.

    Returns
    -------
    ReferenceSubtractionResult with Z_prime and reference metadata.
    """
    if cfg is None:
        cfg = ReferenceConfig()

    n_frames = len(mat.time)
    warnings: List[str] = []

    # --- Select reference frame ---
    M, method, ref_warnings = _select_reference_frame(mat, cfg)
    warnings.extend(ref_warnings)

    M_frame_id = int(mat.frame_ids[M])
    M_time = float(mat.time[M])
    valid_at_M = float(mat.quality_metrics.valid_fraction_per_frame[M])

    # --- Compute Z_prime ---
    # Eq. 1: Z'_{i,j}(k) = Z_{i,j}(k) - Z_{i,j}(M)
    Z_ref_M = mat.Z_def[M, :]                   # (n_sel,)
    Z_prime = mat.Z_def - Z_ref_M[np.newaxis, :] # (n_frames, n_sel)

    # --- Statistics before and after M ---
    before_mask = np.arange(n_frames) < M
    after_mask = np.arange(n_frames) > M
    stats_before = _z_prime_stats(Z_prime, mat.valid, before_mask)
    stats_after = _z_prime_stats(Z_prime, mat.valid, after_mask)

    return ReferenceSubtractionResult(
        Z_prime=Z_prime,
        X_def=mat.X_def,
        Y_def=mat.Y_def,
        M=M,
        M_frame_id=M_frame_id,
        M_time=M_time,
        selection_method=method,
        Z_prime_stats_before_M=stats_before,
        Z_prime_stats_after_M=stats_after,
        valid_fraction_at_M=valid_at_M,
        mat=mat,
        warnings=warnings,
    )

